import {useEffect,useRef} from 'react';
import * as T from 'three';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
gsap.registerPlugin(ScrollTrigger);
export function makeCamera(){
 const root=new T.Group(), groups:T.Group[]=[];
 const ivory=new T.MeshStandardMaterial({color:0xd9d6cc,roughness:.52,metalness:.28}), black=new T.MeshStandardMaterial({color:0x181b18,roughness:.4,metalness:.28}), glass=new T.MeshPhysicalMaterial({color:0x152229,roughness:.09,metalness:.85,clearcoat:1}), steel=new T.MeshStandardMaterial({color:0x999e96,metalness:.9,roughness:.25});
 function part(){const g=new T.Group();root.add(g);groups.push(g);return g}
 function mesh(g:T.Group,geo:T.BufferGeometry,mat:T.Material,x=0,y=0,z=0){const m=new T.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m}
 function cyl(g:T.Group,r:number,h:number,mat:T.Material,x=0,y=0,z=0){let m=mesh(g,new T.CylinderGeometry(r,r,h,96),mat,x,y,z);m.rotation.x=Math.PI/2;return m}
 const rear=part();mesh(rear,new T.SphereGeometry(1.34,64,40,0,Math.PI*2,0,Math.PI),ivory,0,0,-.35).scale.set(1,1,.86);cyl(rear,1.31,1.55,ivory,0,0,-.66);
 const face=part();cyl(face,1.34,.18,ivory,0,0,.2);cyl(face,1.16,.2,black,0,0,.32);mesh(face,new T.TorusGeometry(1.19,.045,12,100),steel,0,0,.45);
 const ir=part();cyl(ir,.98,.09,black,0,0,.49);for(let i=0;i<18;i++){let a=i*Math.PI*2/18;cyl(ir,.083,.042,steel,Math.cos(a)*.81,Math.sin(a)*.81,.55);cyl(ir,.048,.05,glass,Math.cos(a)*.81,Math.sin(a)*.81,.58)}
 const lens=part();cyl(lens,.61,.4,black,0,0,.65);for(let i=0;i<4;i++)mesh(lens,new T.TorusGeometry(.58-i*.07,.025,12,80),steel,0,0,.87+i*.01);cyl(lens,.36,.07,glass,0,0,.94);cyl(lens,.18,.075,black,0,0,.96);mesh(lens,new T.SphereGeometry(.11,24,16),glass,-.06,.08,1.01).scale.z=.15;
 const board=part();mesh(board,new T.BoxGeometry(.91,.91,.055),new T.MeshStandardMaterial({color:0x686e40,roughness:.6}),0,0,-.88);mesh(board,new T.BoxGeometry(.3,.3,.065),black,0,0,-.82);
 const mount=part();mesh(mount,new T.BoxGeometry(.57,.8,.55),ivory,0,-1.22,-.45);let base=mesh(mount,new T.CylinderGeometry(1.1,1.16,.3,64),ivory,0,-1.72,-.43);for(let i=0;i<3;i++){let a=i*2.094;let s=mesh(mount,new T.CylinderGeometry(.07,.07,.02,16),steel,Math.cos(a)*.86,-1.56,-.43+Math.sin(a)*.86);s.rotation.x=0}base.receiveShadow=true;
 for(let i=0;i<4;i++){let a=i*Math.PI/2+.78;cyl(face,.045,.03,steel,Math.cos(a)*1.25,Math.sin(a)*1.25,.31)}
 root.rotation.set(-.08,.55,.05);return {root,groups};
}
export default function Camera({onThumbs}:{onThumbs:(v:string[])=>void}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!ref.current)return;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true})}catch{onThumbs(Array(6).fill('/assets/camera-poster.png'));return}const el=ref.current;renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.setClearColor(0,0);el.appendChild(renderer.domElement);el.classList.add('webgl-ready');renderer.domElement.addEventListener('webglcontextlost',()=>el.classList.remove('webgl-ready'));const scene=new T.Scene(),camera=new T.PerspectiveCamera(32,1,.1,100);camera.position.set(0,.3,9.5);scene.add(new T.HemisphereLight(0xfffdf7,0x54574d,2.4));const key=new T.DirectionalLight(0xfffdf6,3.5);key.position.set(-4,6,6);scene.add(key);const fill=new T.DirectionalLight(0xffffff,2);fill.position.set(4,1,-3);scene.add(fill);const {root,groups}=makeCamera();scene.add(root);const shadow=new T.Mesh(new T.PlaneGeometry(30,30),new T.ShadowMaterial({opacity:.14}));shadow.rotation.x=-Math.PI/2;shadow.position.y=-1.9;shadow.receiveShadow=true;scene.add(shadow);key.castShadow=true;key.shadow.mapSize.set(1024,1024);
const thumbs:string[]=[];renderer.setSize(400,320);camera.aspect=1.25;camera.updateProjectionMatrix();for(let i=0;i<6;i++){const variant=new T.Group();if(i===0){root.visible=true;root.rotation.y=.55}else{root.visible=false;const mat=new T.MeshStandardMaterial({color:0xd9d6cc,roughness:.6,metalness:.15});const add=(geo:T.BufferGeometry,y=0,z=0)=>{const m=new T.Mesh(geo,mat);m.position.set(0,y,z);variant.add(m);return m};if(i===1){const m=add(new T.CylinderGeometry(.75,.75,2.5,64),0,-.5);m.rotation.x=Math.PI/2;add(new T.BoxGeometry(.45,.9,.45),-1,-1.3);const base=add(new T.CylinderGeometry(.8,.8,.2,48),-1.55,-1.3);base.rotation.x=0}else if(i===2||i===3){add(new T.SphereGeometry(1.1,48,32),-.3,-.3);add(new T.CylinderGeometry(1.18,1.25,.35,64),.65,-.3);if(i===3)add(new T.CylinderGeometry(.65,.8,1.2,64),1.2,-.3)}else{add(new T.BoxGeometry(1.2,1.85,.8),0,-.3);add(new T.CylinderGeometry(.65,.75,.15,48),-1.3,-.2);add(new T.BoxGeometry(.2,.6,.2),-1,-.3)}groups.slice(1,4).forEach(g=>{const clone=g.clone();clone.scale.setScalar(i===1?.6:i>3?.46:.65);clone.position.set(0,i>3?.25:-.1,i===1?.55:.45);variant.add(clone)});variant.rotation.y=.5;scene.add(variant)}renderer.render(scene,camera);thumbs.push(renderer.domElement.toDataURL('image/png'));scene.remove(variant)}root.visible=true;onThumbs(thumbs);root.scale.setScalar(1);root.rotation.y=.55;
let progress=0;function render(){const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.render(scene,camera)}const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const trigger=ScrollTrigger.create({trigger:'.story',start:'top top',end:'bottom bottom',scrub:.45,onUpdate:s=>{if(reduced)return;progress=s.progress;const stage=document.querySelector('.story-sticky') as HTMLElement;const copy=document.querySelector('.hero-copy') as HTMLElement;const chapter=document.querySelector('.timeline-copy') as HTMLElement;if(stage){stage.dataset.phase=progress>.54&&progress<.84?'installation':progress>.22&&progress<.54?'engineering':'hero';stage.style.background=progress>.22&&progress<.54?'#242824':'radial-gradient(ellipse at 35% 44%,#f6f4ed 0,#e7e4dc 67%)';stage.style.color=progress>.22&&progress<.54?'#f3f0e9':'#262923'}if(copy)copy.style.opacity=String(Math.max(0,1-(progress-.1)*10));if(chapter){chapter.style.opacity=progress>.2?'1':'0';chapter.innerHTML=progress<.5?'<span>نمای مفهومی ساختار دوربین</span><h2>جزئیات را ببینید.</h2><p>بدنه · حسگر · روشنایی مادون قرمز · لنز</p>':progress<.75?'<span>دوباره، یک تصویر کامل</span><h2>برای فضای شما.</h2><p>از شناخت جزئیات تا انتخاب جای درست.</p>':'<span>انتخابی متناسب با شما</span><h2>هر فضا، یک نگاه.</h2><p>حالا دوربین مناسب خود را پیدا کنید.</p>'}const explode=progress<.34?Math.max(0,(progress-.24)/.1):progress<.42?1:Math.max(0,1-(progress-.42)/.12);groups.forEach((g,i)=>{g.position.z=explode*([-.9,.8,1.6,2.6,-1.7,-.5][i]);g.position.x=explode*(i-2.5)*.38});root.rotation.y=.55+progress*.7;root.rotation.z=.05-progress*.12;root.position.y=progress>.54&&progress<.84?1.4:0;const scale=progress<.14?1:progress<.24?1+(progress-.14)*6:progress<.54?.72:progress<.84?.42:.8;root.scale.setScalar(scale);render()}});const obs=new ResizeObserver(render);obs.observe(el);render();return()=>{trigger.kill();obs.disconnect();scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())}});renderer.dispose();el.replaceChildren()};},[]);return <div ref={ref} className="camera-canvas" aria-label="مدل سه‌بعدی مفهومی دوربین نظارتی"><img className="camera-poster" src="/assets/camera-poster.png" alt="دوربین نظارتی مفهومی"/></div>}
